NeonGeckoCom/neon_mq_connector

neon_mq_connector/connector.py
tests/test_connector.py

Added service id initialization

Service ID

---

neon_mq_connector/connector.py

Added class method for emitting mq messages.

Emitting MQ messages

---

.github/workflows/publish_test_build.yml
.github/workflows/unit_tests.yml

Revert test build workflow dispatch patch

Extend Unit Tests to other Python versions

---

README.md
setup.py

Add basic documentation for getting started.

Add documentation

---

neon_mq_connector/connector.py
tests/test_connector.py

Add param for auto-ack of messages
Add unit test of message sent before queue registration

Make message ack configurable per-service

---

LICENSE.md
neon_mq_connector/__init__.py
neon_mq_connector/config.py
neon_mq_connector/connector.py
neon_mq_connector/utils/__init__.py
neon_mq_connector/utils/connection_utils.py
neon_mq_connector/utils/thread_utils.py
setup.py
tests/test_connector.py
tests/test_utils.py
version.py
version_bump.py

Update file headers and License

Update license to BSD-3

---

neon_mq_connector/connector.py
tests/test_connector.py

Added support for exchange/exchange_type declaration

Support for exchange types declaration

---

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
requirements/requirements.txt
tests/test_backward_compatibility.py
tests/test_connector.py

Fixed order for `register_consumer()` as it broke dependencies

Hotfix (06.01.2022)

---

neon_mq_connector/connector.py
tests/test_connector.py

Feat support for exchanges binding

---

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
requirements/requirements.txt
tests/test_backward_compatibility.py
tests/test_connector.py

Hotfix 06012022

---

neon_mq_connector/connector.py

Refactored publish modules

---

neon_mq_connector/connector.py
neon_mq_connector/utils/connection_utils.py

Fix `is_consuming` to be set True before thread runs forever
Reformat and update docstrings in connector.py

Minor `is_consuming` fix and reformat for style

---

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
tests/test_connector.py

Initial implementation for testing mode resolving based on provided environment

Support for testing coverage

---

neon_mq_connector/connector.py
neon_mq_connector/utils/connection_utils.py
tests/test_backward_compatibility.py
tests/test_connector.py

- Improved stability of consumers by applying retry functionality
- Improved stability of MQ Connector by wrapping run() method with retry() decorator
- Updated retry method to include more detailed logs

Modules Stability Improvement

---

neon_mq_connector/connector.py
neon_mq_connector/utils/rabbit_utils.py
tests/test_connector.py

Added a couple of convenience handlers in order to simplify interaction with MQ Connector

Send/Receive Message Advancements

---

neon_mq_connector/connector.py
neon_mq_connector/utils/connection_utils.py

Minor is_consuming fix and reformat for style

---

neon_mq_connector/connector.py

Added support for configurable runtime properties based on received user config

Runtime properties config support

---

neon_mq_connector/connector.py
neon_mq_connector/utils/rabbit_utils.py

Improving MQ consistency

---

neon_mq_connector/__init__.py
neon_mq_connector/config.py
neon_mq_connector/connector.py
neon_mq_connector/utils/__init__.py
neon_mq_connector/utils/client_utils.py
neon_mq_connector/utils/connection_utils.py
neon_mq_connector/utils/network_utils.py
requirements/requirements.txt
tests/test_backward_compatibility.py
tests/test_config.json
tests/test_connector.py
tests/test_utils.py

Refactor to remove circular dependency on neon_utils
Updates tests to use included configuration instead of GH secret
Cleanup docstrings and PEP

Refactor to remove neon_utils dependency

---

setup.py

Update setup.py to use fully defined file paths
Resolve version automation failure https://github.com/NeonGeckoCom/neon_mq_connector/actions/runs/4767882418/jobs/8476597555

Fix setup.py relative path references

---

.github/workflows/publish_test_build.yml

Removes invalid Docker automation added in #81

Remove invalid Docker automation

---

.github/workflows/publish_release.yml
neon_mq_connector/connector.py
neon_mq_connector/utils/connection_utils.py

Cleanup logging around connection retries
Add default error handler for services not implementing their own
Define params in connector module to resolve reference warnings
Fix automation error introduced in #81

Minor logging and code cleanup

---

neon_mq_connector/connector.py

Handles `message_id` in message context (if present) instead of creating a unique one

Update `message_id` handling for response routing

---

neon_mq_connector/connector.py

Added "is_consumer_alive" flag to ensure graceful termination of the ConsumerThread

Fixing Issues with Consumers termination

---

neon_mq_connector/connector.py
tests/test_connector.py

Raise exception if MQ startup check fails
Add test of MQ restart logic
Add `started` property to easily check if an `MQConnector` instance is started
Should resolve observed issue where re-deploying the backend causes services to initialize without an MQ connection

Handle errors if MQ is not connected at service launch

---

LICENSE.md
neon_mq_connector/__init__.py
neon_mq_connector/config.py
neon_mq_connector/connector.py
neon_mq_connector/consumers/__init__.py
neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/consumers/select_consumer.py
neon_mq_connector/utils/__init__.py
neon_mq_connector/utils/client_utils.py
neon_mq_connector/utils/connection_utils.py
neon_mq_connector/utils/consumer_utils.py
neon_mq_connector/utils/network_utils.py
neon_mq_connector/utils/rabbit_utils.py
neon_mq_connector/utils/thread_utils.py
setup.py
tests/__init__.py
tests/backward_compat_tests.py
tests/fixtures.py
tests/test_connector.py
tests/test_consumers.py
tests/test_utils.py
version.py
version_bump.py

Update copyright notices to 2025

---

neon_mq_connector/connector.py
neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/consumers/select_consumer.py
neon_mq_connector/utils/connection_utils.py
tests/test_consumers.py
tests/test_utils.py

Add a test connection to RMQ as part of  availability tests (in addition to current TCP port check)
Refactor `reconnect` to use an Event instead of sleeping to reduce CPU load
Update logging to reduce duplicated information in `INFO` logs

Improved Startup Connectivity Checks
