NeonGeckoCom/neon_mq_connector

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
tests/test_connector.py

Refactor ~/.local/share/neon/credentials.json to ~/.local/share/neon/mq_config.json for disambiguation
Update unit tests to read mq_config if config.json not available
Encapsulate child process errors in stop_consumers
Refactor test_connector imports to use relative file paths

Minor style changes and unit test bugfixes

---

neon_mq_connector/connector.py

Handle expected exceptions and suppress logging of expected errors
Remove prefetch_count param that caused connector to stop processing requests after 50

Fix Neon API Request Processing

---

neon_mq_connector/__init__.py
neon_mq_connector/config.py
neon_mq_connector/connector.py

Adds option for `MQ` config to be passed in addition to global config with `MQ` as a top-level key
Optionally reads config from standard locations if not provided
Updates `Configuration` class to build config from dict or JSON file

More flexible config

---

neon_mq_connector/connector.py

Replace prefetch_count limit
Set auto_ack to True to ensure queue is cleared on message handling

Limit message handling by consumer threads

---

neon_mq_connector/connector.py
tests/test_connector.py

Move consumer definition inside ConsumerThread init to resolve errors on channel close (https://github.com/pika/pika/issues/1144#issuecomment-521026912)
Add error_func to handle any exceptions raised in consumers
Add unit testing of error callback
Adds `register_consumer` convenience method
TODO: Drop compatibility checks before push to master
Adds functionality to address: https://github.com/NeonGeckoCom/neon_api_proxy/issues/18

Resolve errors closing connections, Add Error Handling

---

neon_mq_connector/config.py
neon_mq_connector/connector.py

Update MQ Connector to optionally read NEON_MQ_CONFIG_PATH envvar to match functionality in neon_api_proxy
Mark MQConnector config param as optional

Update config handling

---

neon_mq_connector/connector.py
neon_mq_connector/utils/__init__.py
neon_mq_connector/utils/connection_utils.py
requirements/requirements.txt
tests/test_utils.py

Add method wait_for_mq_startup with unit test
Handle ConsumerThread init retry in case MQ server is starting up

Wait for MQ Server for Docker Compose support

---

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
neon_mq_connector/utils/client_utils.py
neon_mq_connector/utils/connection_utils.py
requirements/requirements.txt
tests/test_connector.py
tests/test_utils.py

This moves `neon_utils.mq_utils` to `neon_mq_connector.utils.client_utils` to remove a circular dependency. With this change,
`neon_utils` can specify `neon_mq_connector` as an optional dependency for backwards-compatibility only

Implement MQ client utils to resolve circular dependency with neon_utils

---

neon_mq_connector/connector.py
tests/test_connector.py

Ensure config is initialized before first reference
Add init tests for MQConnector class

Make Configuration reference safe with unit tests

---

README.md
neon_mq_connector/config.py
neon_mq_connector/connector.py
neon_mq_connector/utils/client_utils.py
neon_mq_connector/utils/connection_utils.py

Update `load_neon_mq_config` to fallback to ovos_config
Mark legacy `Configuration` class as deprecated
Log warning for legacy configuration files

Implement ovos-config and log deprecation for old config files

---

.github/workflows/unit_tests.yml
neon_mq_connector/connector.py
neon_mq_connector/utils/client_utils.py
tests/test_backward_compatibility.py
tests/test_connector.py

Cleanup logging to help troubleshoot responses
Handle `message_id` in context for `neon_mq_connector` response compat.

Update logging and response routing

---

neon_mq_connector/utils/client_utils.py

Support matching `message_id` from response context for compat.
This adds context handling to check for an origin `message_id`, but we should specify more precisely when `message_id` is generated vs copied from an incoming message and what a response is expected to return

Update message_id handling for iris compat

---

.github/workflows/unit_tests.yml
neon_mq_connector/utils/client_utils.py
requirements/requirements.txt
tests/test_utils.py

Update dependency to allow for ovos-config~=0.1
https://github.com/NeonGeckoCom/NeonCore/pull/708

Update OVOS dependencies

---

.github/workflows/unit_tests.yml
neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/consumers/select_consumer.py
neon_mq_connector/utils/consumer_utils.py
neon_mq_connector/utils/rabbit_utils.py
requirements/test_requirements.txt
tests/__init__.py
tests/backward_compat_tests.py
tests/fixtures.py
tests/test_connector.py
tests/test_consumers.py
tests/test_utils.py

Refactor tests to use a local RMQ instance instead of configured remote
Allow non-backwards-compat tests to run in parallel
Includes consumer refactoring to better report `is_consuming` state
Adds handling to `select_consumer` to differentiate socket closure on shutdown vs on error
Adds shutdown handling to `select_consumer` to wait for the connection to close before joining the thread
Allows decorated callback methods to be called directly with a dict `body` input
Allows decorating callback functions in addition to methods

Update tests to use temporary RMQ instance and improve coverage

---

neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/consumers/select_consumer.py
tests/test_consumers.py

Update `SelectConsumerThread` to pass exceptions to `self.error_func` to match `BlockingConsumerThread`
Handle channel/connection closed exceptions explicitly in `SelectConsumerThread`
Update `BlockingConsumerThread` to ensure connection is closed exactly once
Update tests to check for expected error callbacks
Alternate solution to #106

Improve connection close and error handling

---

neon_mq_connector/connector.py
neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/utils/client_utils.py
tests/test_utils.py

https://github.com/NeonGeckoCom/neon-iris/pull/65 highlighted that `stop` does not close the connection
`shutdown` provides a method for cleaning up after a `NeonMQHandler` instance with unit test coverage

Define `shutdown` method for NeonMQHandler with unit test coverage

---

neon_mq_connector/connector.py
neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/consumers/select_consumer.py

Prevent attempting to restart an exclusive consumer (will fail repeatedly)
Updates subscriber queues to not be exclusive
Ensures an asyncio event loop is always defined in SelectConsumerThreads
Noted in Sentry https://neon-ai.sentry.io/issues/6219883443/?project=4507250609356800&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
A neon-llm-vllm alpha container is deployed to the alpha namespace with these changes integrated to resolve Sentry logged errors

Resolve observed connection errors

---

neon_mq_connector/consumers/select_consumer.py

Update StreamLost handling from error to warning to prevent non-actionable errors
Refactor connection close error log to accurately state "closed" instead of "closing" 
https://neon-ai.sentry.io/issues/6117742740/events/8741afbd379f439a843d69094c0a63fe/

Update logging in select consumer close

---

README.md
neon_mq_connector/connector.py
neon_mq_connector/consumers/select_consumer.py
neon_mq_connector/utils/client_utils.py
tests/test_utils.py

Update default async behavior to `True`
Read async behavior from envvar `MQ_ASYNC_CONSUMERS`
Update documentation to reflect changes in default and configuration

Update default async consumer behavior and configuration

---

neon_mq_connector/connector.py
requirements/requirements.txt
tests/test_connector.py

Update `emit_mq_message` to allow either BlockingConnection or SelectConnection objects
Add unit test coverage for `emit_mq_message`
- Needs rebase after merge of https://github.com/NeonGeckoCom/neon_mq_connector/pull/113

Support Select Connections in `emit_mq_message`

---

neon_mq_connector/connector.py
neon_mq_connector/utils/connection_utils.py
tests/test_utils.py

Add specific handling for RMQ checks without a configured vhost
Add test coverage for `check_rmq_is_available`
Update logging
Follow-up to #117

Handle RMQ checks with default vhost

---

neon_mq_connector/connector.py

Refactor `_started` to `_consumers_started` to avoid conflicts in classes that also extend `Thread`
Observed in an alpha deployment testing https://github.com/NeonGeckoCom/neon-iris/pull/67

Update param name to avoid conflict with `threading.Thread`

---

neon_mq_connector/connector.py
tests/test_connector.py

Ensure `message_id` is always a valid string
Add unit test coverage for `None` value handling
`None` value noted in https://neon-ai.sentry.io/issues/6247512848/events/4190e34724534fd181b2369413f5f8b3/

Update to ensure `message_id` is not None

---

neon_mq_connector/connector.py
neon_mq_connector/consumers/select_consumer.py
neon_mq_connector/utils/connection_utils.py
tests/test_utils.py

Update `retry` decorator to allow decorating functions and staticmethods
Update `retry` to raise unhandled exceptions with unit test coverage
Update observer to default `False` for SelectConsumer instances that implement their own reconnect logic
Add more specific error handling and logging
Closes #125
Currently deployed with ChatGPT in the alpha namespace

Raise unhandled retry exceptions

---

neon_mq_connector/utils/client_utils.py

Explicitly delete response queues in `send_mq_request` to prevent accumulation of unused queues in RMQ broker
vLLM and ChatGPT have been updated on Alpha with this change and with chatbotsforumalpha running, the number of queues appears to be static (543) when it was previously growing at a rate of about 10 queues/minute (measured over a 10 minute span)

Clean up response queues after single use

---

neon_mq_connector/consumers/blocking_consumer.py
neon_mq_connector/utils/client_utils.py
neon_mq_connector/utils/connection_utils.py

Add `SuppressPikaLogging` helper class to disable Pika exception logging around specific methods
Add unit test coverage for logging helper class
Ignore `ConnectionClosed` exceptions around connection closure
https://neon-ai.sentry.io/issues/6117780109/events/0dc8fa02ee394e8e8e7ac0ce2cab6296/
https://neon-ai.sentry.io/issues/6036780814/events/4bfdd7b2598f4cb1b17304082ce6e295/
https://neon-ai.sentry.io/issues/6036781170/events/4366af6f212145568f08a4d18e1ce29d/
https://neon-ai.sentry.io/issues/6036781181/events/239d88d9bf0f4832aa282da40c48f515/

Suppress pika error logging around "normal" situations

---

neon_mq_connector/connector.py
neon_mq_connector/utils/client_utils.py
tests/test_utils.py

Ensure `send_mq_request` cleans up created connections
Reduce queue creation logs from `INFO` to `DEBUG`
Includes test coverage missed in #128 
Deployed with ChatGPT in the Alpha namespace

Update logging and cleanup created MQ Connections

---

neon_mq_connector/consumers/blocking_consumer.py

Add more exception handling around BlockingConsumerThread connection close to address Sentry logged errors
https://neon-ai.sentry.io/issues/6179009031/events/f9a1d4c1a6434f52bbeaf284e7ad7bd0/
https://neon-ai.sentry.io/issues/6328852371/events/7e56c0525e044b718f567db9c1034524/
https://neon-ai.sentry.io/issues/6227576687/events/f58b1fe25f7c4a9690480fa1e88325bc/
https://neon-ai.sentry.io/issues/6328811787/events/ddd3cfe1b37544d080847a5795413d24/
https://neon-ai.sentry.io/issues/6328819692/events/c3db6b5161cd4acaa1f244f891cac4fb/
https://neon-ai.sentry.io/issues/6328874042/events/849532317e58441aace7a9ed5d4ce603/
https://neon-ai.sentry.io/issues/6315750018/events/0ffa39ad2ddc46e384033e6124f4ef29/
Validated in Alpha with ChatGPT container

Add connection close exception handling

---

neon_mq_connector/connector.py
tests/test_connector.py

Add `check_health` method to report if an `MQConnector` instance is healthy

Implement a `check_health` method to check for failed listener threads
